spring:
  application:
    name: spring-cloud-netflix-ribbon-eureka-server

server:
  port: 8888

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/